bash scripts/download_checkpoint.sh jpeg-5 &
bash scripts/download_checkpoint.sh jpeg-10 &
bash scripts/download_checkpoint.sh sr4x-pool &
bash scripts/download_checkpoint.sh sr4x-bicubic &
bash scripts/download_checkpoint.sh blur-uni &
bash scripts/download_checkpoint.sh blur-gauss &
bash scripts/download_checkpoint.sh inpaint-center &
bash scripts/download_checkpoint.sh inpaint-freeform1020 &
bash scripts/download_checkpoint.sh inpaint-freeform2030 &